repos
-   repo: https://github.com/mpratsch/pre-commit-hooks.git
    rev: master # or tag specific like 1.0.0
    hooks:
    - id: check-rcloud-version
      stages: [post-checkout]
      always_run: true:
