-   id: check-rcloud-version
    name: Check rCloud Version
    description: This hook checks if a new release version exists and overwrites some file.
    entry: pre_commit_hooks/check_rcloud_version
    language: script
    stages: [post-checkout]
